### ISSUE TITLE
身分證尾數分流

### ISSUE THREAD

**Issue by schuang** [kiang/antigen#2]
建議加上提醒「身分證尾數分流」的規定（也許可以加在顯示藥局資訊的備註欄）

**Comment by kiang** [comment]
感謝建議，加進去了
![Screenshot from 2022-05-03 14-46-20](https://user-images.githubusercontent.com/47844/166414062-c975ffba-7f61-4826-a427-6ea11959f4f9.png)

75ebbd1eb97040c3b9d925262dcc36332b6c2c9f

**Comment by schuang** [comment]
感謝🙏
